/*
 * Laptop GPUs and the machines that ship them.
 *
 * Laptop GPUs share a marketing name with their desktop cousins but are
 * different, cut-down silicon — an "RTX 5080 Laptop" is nowhere near an RTX
 * 5080. More importantly, the SAME laptop GPU performs very differently
 * depending on the power the chassis lets it draw (TGP). A 4060 at 140 W and a
 * 4060 at 65 W are not the same product, which is why every machine below
 * records its own TGP and the finder ranks on the resulting effective figure
 * rather than on the GPU name.
 *
 * Performance figures use the same index as the desktop database
 * (desktop RTX 4090 = 100) so the two are directly comparable.
 */

import type { Brand } from "./gpus";

export interface LaptopGpu {
  id: string;
  name: string;
  short: string;
  brand: Brand;
  generation: string;
  vram: number;
  vramType: string;
  memoryBus: number;
  shaders: number;
  /** Manufacturer-allowed TGP range, excluding Dynamic Boost. */
  minTgp: number;
  maxTgp: number;
  /** 1440p raster index at max TGP, desktop RTX 4090 = 100. */
  perfAtMaxTgp: number;
  /** 1440p ray tracing index at max TGP. */
  rtAtMaxTgp: number;
  /** Desktop card this is loosely comparable to, for cross-referencing. */
  desktopCousin?: string;
  upscaling: string;
}

export const LAPTOP_GPUS: LaptopGpu[] = [
  {
    id: "rtx-5090-laptop",
    name: "GeForce RTX 5090 Laptop",
    short: "RTX 5090",
    brand: "NVIDIA",
    generation: "RTX 50 (Blackwell)",
    vram: 24,
    vramType: "GDDR7",
    memoryBus: 256,
    shaders: 10496,
    minTgp: 95,
    maxTgp: 175,
    perfAtMaxTgp: 63,
    rtAtMaxTgp: 64,
    desktopCousin: "rtx-5080",
    upscaling: "DLSS 4 (Multi Frame Gen)",
  },
  {
    id: "rtx-5080-laptop",
    name: "GeForce RTX 5080 Laptop",
    short: "RTX 5080",
    brand: "NVIDIA",
    generation: "RTX 50 (Blackwell)",
    vram: 16,
    vramType: "GDDR7",
    memoryBus: 256,
    shaders: 7680,
    minTgp: 95,
    maxTgp: 175,
    perfAtMaxTgp: 55,
    rtAtMaxTgp: 56,
    desktopCousin: "rtx-5070",
    upscaling: "DLSS 4 (Multi Frame Gen)",
  },
  {
    id: "rtx-5070-ti-laptop",
    name: "GeForce RTX 5070 Ti Laptop",
    short: "RTX 5070 Ti",
    brand: "NVIDIA",
    generation: "RTX 50 (Blackwell)",
    vram: 12,
    vramType: "GDDR7",
    memoryBus: 192,
    shaders: 5888,
    minTgp: 80,
    maxTgp: 140,
    perfAtMaxTgp: 46,
    rtAtMaxTgp: 47,
    desktopCousin: "rtx-5060-ti-16",
    upscaling: "DLSS 4 (Multi Frame Gen)",
  },
  {
    id: "rtx-5070-laptop",
    name: "GeForce RTX 5070 Laptop",
    short: "RTX 5070",
    brand: "NVIDIA",
    generation: "RTX 50 (Blackwell)",
    vram: 8,
    vramType: "GDDR7",
    memoryBus: 128,
    shaders: 4608,
    minTgp: 50,
    maxTgp: 115,
    perfAtMaxTgp: 36,
    rtAtMaxTgp: 37,
    desktopCousin: "rtx-5060",
    upscaling: "DLSS 4 (Multi Frame Gen)",
  },
  {
    id: "rtx-5060-laptop",
    name: "GeForce RTX 5060 Laptop",
    short: "RTX 5060",
    brand: "NVIDIA",
    generation: "RTX 50 (Blackwell)",
    vram: 8,
    vramType: "GDDR7",
    memoryBus: 128,
    shaders: 3328,
    minTgp: 45,
    maxTgp: 115,
    perfAtMaxTgp: 30,
    rtAtMaxTgp: 31,
    upscaling: "DLSS 4 (Multi Frame Gen)",
  },
  {
    id: "rtx-4090-laptop",
    name: "GeForce RTX 4090 Laptop",
    short: "RTX 4090",
    brand: "NVIDIA",
    generation: "RTX 40 (Ada Lovelace)",
    vram: 16,
    vramType: "GDDR6",
    memoryBus: 256,
    shaders: 9728,
    minTgp: 80,
    maxTgp: 175,
    perfAtMaxTgp: 58,
    rtAtMaxTgp: 57,
    desktopCousin: "rtx-4070-ti-super",
    upscaling: "DLSS 4 (Frame Gen)",
  },
  {
    id: "rtx-4080-laptop",
    name: "GeForce RTX 4080 Laptop",
    short: "RTX 4080",
    brand: "NVIDIA",
    generation: "RTX 40 (Ada Lovelace)",
    vram: 12,
    vramType: "GDDR6",
    memoryBus: 192,
    shaders: 7424,
    minTgp: 60,
    maxTgp: 175,
    perfAtMaxTgp: 50,
    rtAtMaxTgp: 50,
    desktopCousin: "rtx-4070-super",
    upscaling: "DLSS 4 (Frame Gen)",
  },
  {
    id: "rtx-4070-laptop",
    name: "GeForce RTX 4070 Laptop",
    short: "RTX 4070",
    brand: "NVIDIA",
    generation: "RTX 40 (Ada Lovelace)",
    vram: 8,
    vramType: "GDDR6",
    memoryBus: 128,
    shaders: 4608,
    minTgp: 35,
    maxTgp: 140,
    perfAtMaxTgp: 37,
    rtAtMaxTgp: 37,
    desktopCousin: "rtx-4060-ti-8",
    upscaling: "DLSS 4 (Frame Gen)",
  },
  {
    id: "rtx-4060-laptop",
    name: "GeForce RTX 4060 Laptop",
    short: "RTX 4060",
    brand: "NVIDIA",
    generation: "RTX 40 (Ada Lovelace)",
    vram: 8,
    vramType: "GDDR6",
    memoryBus: 128,
    shaders: 3072,
    minTgp: 35,
    maxTgp: 140,
    perfAtMaxTgp: 29,
    rtAtMaxTgp: 29,
    desktopCousin: "rtx-4060",
    upscaling: "DLSS 4 (Frame Gen)",
  },
  {
    id: "rtx-4050-laptop",
    name: "GeForce RTX 4050 Laptop",
    short: "RTX 4050",
    brand: "NVIDIA",
    generation: "RTX 40 (Ada Lovelace)",
    vram: 6,
    vramType: "GDDR6",
    memoryBus: 96,
    shaders: 2560,
    minTgp: 35,
    maxTgp: 115,
    perfAtMaxTgp: 23,
    rtAtMaxTgp: 23,
    upscaling: "DLSS 4 (Frame Gen)",
  },
  {
    id: "rx-7900m",
    name: "Radeon RX 7900M",
    short: "RX 7900M",
    brand: "AMD",
    generation: "RX 7000 (RDNA 3)",
    vram: 16,
    vramType: "GDDR6",
    memoryBus: 256,
    shaders: 4608,
    minTgp: 145,
    maxTgp: 180,
    perfAtMaxTgp: 45,
    rtAtMaxTgp: 34,
    desktopCousin: "rx-7800-xt",
    upscaling: "FSR 3.1 + Frame Gen",
  },
  {
    id: "rx-7700s",
    name: "Radeon RX 7700S",
    short: "RX 7700S",
    brand: "AMD",
    generation: "RX 7000 (RDNA 3)",
    vram: 8,
    vramType: "GDDR6",
    memoryBus: 128,
    shaders: 2048,
    minTgp: 75,
    maxTgp: 100,
    perfAtMaxTgp: 25,
    rtAtMaxTgp: 18,
    desktopCousin: "rx-7600",
    upscaling: "FSR 3.1 + Frame Gen",
  },
];

export const LAPTOP_GPU_BY_ID: Record<string, LaptopGpu> = Object.fromEntries(
  LAPTOP_GPUS.map((g) => [g.id, g]),
);

export interface Laptop {
  id: string;
  name: string;
  brand: string;
  year: number;
  gpuId: string;
  /** The TGP this specific machine allows, excluding Dynamic Boost. */
  tgp: number;
  cpu: string;
  ram: number;
  ramType: string;
  ramUpgradable: boolean;
  storage: number;
  screenSize: number;
  resolution: string;
  refresh: number;
  panel: string;
  weight: number;
  batteryWh: number;
  thickness: number;
  /** USD list price and typical Indian street price including GST. */
  msrp: number;
  inr: number;
  indiaAvailability: string;
  notes: string;
}

/*
 * Prices are for the configuration listed. Indian figures are typical street
 * prices including GST and move constantly with sales and stock — confirm
 * before buying. Laptop configurations vary a lot within a model name, so
 * always check the TGP and panel of the exact SKU you are looking at.
 */
export const LAPTOPS: Laptop[] = [
  {
    id: "rog-strix-scar-18-2025",
    name: "ROG Strix SCAR 18",
    brand: "ASUS",
    year: 2025,
    gpuId: "rtx-5090-laptop",
    tgp: 175,
    cpu: "Core Ultra 9 275HX",
    ram: 32,
    ramType: "DDR5-5600",
    ramUpgradable: true,
    storage: 2000,
    screenSize: 18,
    resolution: "2560 x 1600",
    refresh: 240,
    panel: "Mini LED",
    weight: 3.1,
    batteryWh: 90,
    thickness: 23.9,
    msrp: 3999,
    inr: 449990,
    indiaAvailability: "Limited",
    notes: "Full 175 W plus Dynamic Boost; among the fastest laptops you can buy.",
  },
  {
    id: "predator-helios-18-2025",
    name: "Predator Helios 18 AI",
    brand: "Acer",
    year: 2025,
    gpuId: "rtx-5090-laptop",
    tgp: 175,
    cpu: "Core Ultra 9 275HX",
    ram: 32,
    ramType: "DDR5-6400",
    ramUpgradable: true,
    storage: 2000,
    screenSize: 18,
    resolution: "3840 x 2400",
    refresh: 120,
    panel: "Mini LED",
    weight: 3.4,
    batteryWh: 99,
    thickness: 27,
    msrp: 3799,
    inr: 429990,
    indiaAvailability: "Limited",
    notes: "4K Mini LED panel; heavy, but the cooling sustains full power.",
  },
  {
    id: "msi-titan-18-hx-2025",
    name: "Titan 18 HX",
    brand: "MSI",
    year: 2025,
    gpuId: "rtx-5090-laptop",
    tgp: 175,
    cpu: "Core Ultra 9 275HX",
    ram: 64,
    ramType: "DDR5-6400",
    ramUpgradable: true,
    storage: 2000,
    screenSize: 18,
    resolution: "3840 x 2400",
    refresh: 120,
    panel: "Mini LED",
    weight: 3.6,
    batteryWh: 99,
    thickness: 32,
    msrp: 4999,
    inr: 549990,
    indiaAvailability: "Limited",
    notes: "Desktop-replacement class: 64 GB RAM, mechanical keyboard, very heavy.",
  },
  {
    id: "razer-blade-16-2025",
    name: "Blade 16",
    brand: "Razer",
    year: 2025,
    gpuId: "rtx-5090-laptop",
    tgp: 160,
    cpu: "Ryzen AI 9 HX 370",
    ram: 32,
    ramType: "LPDDR5X-8000",
    ramUpgradable: false,
    storage: 1000,
    screenSize: 16,
    resolution: "2560 x 1600",
    refresh: 240,
    panel: "OLED",
    weight: 2.14,
    batteryWh: 90,
    thickness: 14.9,
    msrp: 4499,
    inr: 479990,
    indiaAvailability: "Limited",
    notes: "Thinnest 5090 machine; soldered RAM and a price premium for the chassis.",
  },
  {
    id: "alienware-16-area51-2025",
    name: "Alienware 16 Area-51",
    brand: "Dell",
    year: 2025,
    gpuId: "rtx-5080-laptop",
    tgp: 175,
    cpu: "Core Ultra 9 275HX",
    ram: 32,
    ramType: "DDR5-6400",
    ramUpgradable: true,
    storage: 1000,
    screenSize: 16,
    resolution: "2560 x 1600",
    refresh: 240,
    panel: "IPS",
    weight: 3.4,
    batteryWh: 96,
    thickness: 28.5,
    msrp: 3399,
    inr: 349990,
    indiaAvailability: "Widely available",
    notes: "Thick chassis built around sustained power rather than portability.",
  },
  {
    id: "legion-pro-7i-2025",
    name: "Legion Pro 7i",
    brand: "Lenovo",
    year: 2025,
    gpuId: "rtx-5080-laptop",
    tgp: 175,
    cpu: "Core Ultra 9 275HX",
    ram: 32,
    ramType: "DDR5-6400",
    ramUpgradable: true,
    storage: 1000,
    screenSize: 16,
    resolution: "2560 x 1600",
    refresh: 240,
    panel: "IPS",
    weight: 2.72,
    batteryWh: 99,
    thickness: 25.9,
    msrp: 3399,
    inr: 319990,
    indiaAvailability: "Widely available",
    notes: "Full power in a comparatively sane weight; strong cooling reputation.",
  },
  {
    id: "rog-zephyrus-g16-2025",
    name: "ROG Zephyrus G16",
    brand: "ASUS",
    year: 2025,
    gpuId: "rtx-5080-laptop",
    tgp: 115,
    cpu: "Core Ultra 9 275HX",
    ram: 32,
    ramType: "LPDDR5X-7467",
    ramUpgradable: false,
    storage: 1000,
    screenSize: 16,
    resolution: "2560 x 1600",
    refresh: 240,
    panel: "OLED",
    weight: 1.95,
    batteryWh: 90,
    thickness: 16.4,
    msrp: 2999,
    inr: 279990,
    indiaAvailability: "Widely available",
    notes: "Thin-and-light build: the 5080 runs well below its 175 W ceiling.",
  },
  {
    id: "alienware-m18-r2-2024",
    name: "Alienware m18 R2",
    brand: "Dell",
    year: 2024,
    gpuId: "rtx-4090-laptop",
    tgp: 175,
    cpu: "Core i9-14900HX",
    ram: 32,
    ramType: "DDR5-5600",
    ramUpgradable: true,
    storage: 2000,
    screenSize: 18,
    resolution: "2560 x 1600",
    refresh: 165,
    panel: "IPS",
    weight: 4.2,
    batteryWh: 97,
    thickness: 26.7,
    msrp: 3299,
    inr: 399990,
    indiaAvailability: "End of life",
    notes: "Last-gen flagship, often discounted; extremely heavy at 4.2 kg.",
  },
  {
    id: "hp-omen-16-2025",
    name: "OMEN 16",
    brand: "HP",
    year: 2025,
    gpuId: "rtx-5070-ti-laptop",
    tgp: 140,
    cpu: "Core Ultra 9 275HX",
    ram: 32,
    ramType: "DDR5-5600",
    ramUpgradable: true,
    storage: 1000,
    screenSize: 16,
    resolution: "2560 x 1600",
    refresh: 240,
    panel: "IPS",
    weight: 2.4,
    batteryWh: 83,
    thickness: 23.5,
    msrp: 2299,
    inr: 219990,
    indiaAvailability: "Widely available",
    notes: "Runs the 5070 Ti at its full 140 W in a mainstream chassis.",
  },
  {
    id: "predator-helios-neo-16-2025",
    name: "Predator Helios Neo 16",
    brand: "Acer",
    year: 2025,
    gpuId: "rtx-5070-laptop",
    tgp: 115,
    cpu: "Core Ultra 9 275HX",
    ram: 16,
    ramType: "DDR5-5600",
    ramUpgradable: true,
    storage: 1000,
    screenSize: 16,
    resolution: "2560 x 1600",
    refresh: 180,
    panel: "IPS",
    weight: 2.7,
    batteryWh: 76,
    thickness: 25.9,
    msrp: 1799,
    inr: 169990,
    indiaAvailability: "Widely available",
    notes: "Full-power 5070 at a mid price; heavier than the thin-and-lights.",
  },
  {
    id: "legion-5i-2025",
    name: "Legion 5i",
    brand: "Lenovo",
    year: 2025,
    gpuId: "rtx-5070-laptop",
    tgp: 115,
    cpu: "Core Ultra 7 255HX",
    ram: 16,
    ramType: "DDR5-5600",
    ramUpgradable: true,
    storage: 1000,
    screenSize: 16,
    resolution: "2560 x 1600",
    refresh: 165,
    panel: "IPS",
    weight: 2.4,
    batteryWh: 80,
    thickness: 24.2,
    msrp: 1599,
    inr: 154990,
    indiaAvailability: "Widely available",
    notes: "Balanced mainstream pick; 5070 at its full 115 W.",
  },
  {
    id: "rog-zephyrus-g14-2025",
    name: "ROG Zephyrus G14",
    brand: "ASUS",
    year: 2025,
    gpuId: "rtx-5070-laptop",
    tgp: 90,
    cpu: "Ryzen AI 9 HX 370",
    ram: 32,
    ramType: "LPDDR5X-7500",
    ramUpgradable: false,
    storage: 1000,
    screenSize: 14,
    resolution: "2880 x 1800",
    refresh: 120,
    panel: "OLED",
    weight: 1.5,
    batteryWh: 73,
    thickness: 15.9,
    msrp: 1999,
    inr: 184990,
    indiaAvailability: "Widely available",
    notes: "Best-in-class portability; you pay for it in TGP and in price.",
  },
  {
    id: "dell-g16-2024",
    name: "G16 7630",
    brand: "Dell",
    year: 2024,
    gpuId: "rtx-4070-laptop",
    tgp: 140,
    cpu: "Core i9-13900HX",
    ram: 16,
    ramType: "DDR5-4800",
    ramUpgradable: true,
    storage: 1000,
    screenSize: 16,
    resolution: "2560 x 1600",
    refresh: 240,
    panel: "IPS",
    weight: 2.79,
    batteryWh: 86,
    thickness: 26.9,
    msrp: 1599,
    inr: 149990,
    indiaAvailability: "Limited",
    notes: "Full 140 W 4070; frequently discounted now that the 50-series is out.",
  },
  {
    id: "aorus-16x-2024",
    name: "Aorus 16X",
    brand: "Gigabyte",
    year: 2024,
    gpuId: "rtx-4070-laptop",
    tgp: 140,
    cpu: "Core i7-14650HX",
    ram: 16,
    ramType: "DDR5-5600",
    ramUpgradable: true,
    storage: 1000,
    screenSize: 16,
    resolution: "1920 x 1200",
    refresh: 165,
    panel: "IPS",
    weight: 2.3,
    batteryWh: 76,
    thickness: 23,
    msrp: 1399,
    inr: 134990,
    indiaAvailability: "Limited",
    notes: "Full-power 4070 at a keen price; only a 1200p panel.",
  },
  {
    id: "hp-omen-transcend-14-2024",
    name: "OMEN Transcend 14",
    brand: "HP",
    year: 2024,
    gpuId: "rtx-4060-laptop",
    tgp: 65,
    cpu: "Core Ultra 9 185H",
    ram: 16,
    ramType: "LPDDR5X-7467",
    ramUpgradable: false,
    storage: 1000,
    screenSize: 14,
    resolution: "2880 x 1800",
    refresh: 120,
    panel: "OLED",
    weight: 1.63,
    batteryWh: 71,
    thickness: 17.9,
    msrp: 1499,
    inr: 139990,
    indiaAvailability: "Limited",
    notes: "A 4060 held to 65 W — the clearest example of TGP mattering more than the name.",
  },
  {
    id: "legion-slim-5-2024",
    name: "Legion Slim 5",
    brand: "Lenovo",
    year: 2024,
    gpuId: "rtx-4060-laptop",
    tgp: 115,
    cpu: "Ryzen 7 8845HS",
    ram: 16,
    ramType: "DDR5-5600",
    ramUpgradable: true,
    storage: 512,
    screenSize: 16,
    resolution: "2560 x 1600",
    refresh: 165,
    panel: "IPS",
    weight: 2.3,
    batteryWh: 80,
    thickness: 21.5,
    msrp: 1199,
    inr: 114990,
    indiaAvailability: "Widely available",
    notes: "Good balance of weight, panel and sustained power for the money.",
  },
  {
    id: "msi-katana-15-2024",
    name: "Katana 15",
    brand: "MSI",
    year: 2024,
    gpuId: "rtx-4060-laptop",
    tgp: 105,
    cpu: "Core i7-13620H",
    ram: 16,
    ramType: "DDR5-5200",
    ramUpgradable: true,
    storage: 1000,
    screenSize: 15.6,
    resolution: "1920 x 1080",
    refresh: 144,
    panel: "IPS",
    weight: 2.25,
    batteryWh: 53,
    thickness: 24.9,
    msrp: 1099,
    inr: 99990,
    indiaAvailability: "Widely available",
    notes: "Cheap 4060 machine; small battery and a basic 1080p panel.",
  },
  {
    id: "lenovo-loq-15-2024",
    name: "LOQ 15",
    brand: "Lenovo",
    year: 2024,
    gpuId: "rtx-4060-laptop",
    tgp: 105,
    cpu: "Core i7-13650HX",
    ram: 16,
    ramType: "DDR5-4800",
    ramUpgradable: true,
    storage: 512,
    screenSize: 15.6,
    resolution: "1920 x 1080",
    refresh: 144,
    panel: "IPS",
    weight: 2.38,
    batteryWh: 60,
    thickness: 23.9,
    msrp: 1049,
    inr: 94990,
    indiaAvailability: "Widely available",
    notes: "Popular budget pick in India; 512 GB fills up fast.",
  },
  {
    id: "asus-tuf-a15-2024",
    name: "TUF Gaming A15",
    brand: "ASUS",
    year: 2024,
    gpuId: "rtx-4060-laptop",
    tgp: 140,
    cpu: "Ryzen 7 7435HS",
    ram: 16,
    ramType: "DDR5-4800",
    ramUpgradable: true,
    storage: 512,
    screenSize: 15.6,
    resolution: "1920 x 1080",
    refresh: 144,
    panel: "IPS",
    weight: 2.2,
    batteryWh: 90,
    thickness: 22.4,
    msrp: 1099,
    inr: 89990,
    indiaAvailability: "Widely available",
    notes: "The full 140 W 4060 at a budget price — the value benchmark here.",
  },
  {
    id: "asus-tuf-a16-2024",
    name: "TUF Gaming A16",
    brand: "ASUS",
    year: 2024,
    gpuId: "rx-7700s",
    tgp: 100,
    cpu: "Ryzen 7 7735HS",
    ram: 16,
    ramType: "DDR5-4800",
    ramUpgradable: true,
    storage: 512,
    screenSize: 16,
    resolution: "1920 x 1200",
    refresh: 165,
    panel: "IPS",
    weight: 2.2,
    batteryWh: 90,
    thickness: 22.9,
    msrp: 1199,
    inr: 109990,
    indiaAvailability: "Limited",
    notes: "All-AMD build; weaker ray tracing and no DLSS.",
  },
  {
    id: "hp-victus-15-2024",
    name: "Victus 15",
    brand: "HP",
    year: 2024,
    gpuId: "rtx-4050-laptop",
    tgp: 95,
    cpu: "Core i5-13420H",
    ram: 16,
    ramType: "DDR4-3200",
    ramUpgradable: true,
    storage: 512,
    screenSize: 15.6,
    resolution: "1920 x 1080",
    refresh: 144,
    panel: "IPS",
    weight: 2.29,
    batteryWh: 52.5,
    thickness: 23.5,
    msrp: 799,
    inr: 69990,
    indiaAvailability: "Widely available",
    notes: "Entry point into gaming laptops; 6 GB of VRAM is the limiting factor.",
  },
  {
    id: "acer-nitro-v-15-2024",
    name: "Nitro V 15",
    brand: "Acer",
    year: 2024,
    gpuId: "rtx-4050-laptop",
    tgp: 75,
    cpu: "Core i5-13420H",
    ram: 16,
    ramType: "DDR5-4800",
    ramUpgradable: true,
    storage: 512,
    screenSize: 15.6,
    resolution: "1920 x 1080",
    refresh: 144,
    panel: "IPS",
    weight: 2.1,
    batteryWh: 57,
    thickness: 22.9,
    msrp: 749,
    inr: 64990,
    indiaAvailability: "Widely available",
    notes: "Cheapest way in, but the 4050 is throttled to 75 W.",
  },
];

/**
 * Effective performance for a GPU held at a given TGP.
 *
 * Performance scales sub-linearly with power — the last watts buy very little.
 * The 0.35 exponent lands within a few percent of published TGP-scaling tests
 * (a 175 W part cut to 105 W loses roughly 15%), but it is a model, not a
 * measurement of any specific machine.
 */
export function perfAtTgp(perfAtMax: number, tgp: number, maxTgp: number): number {
  const ratio = Math.min(1, tgp / maxTgp);
  return +(perfAtMax * Math.pow(ratio, 0.35)).toFixed(1);
}

export interface DerivedLaptop extends Laptop {
  gpu: LaptopGpu;
  /** Share of the GPU's rated TGP this machine allows, 0-1. */
  tgpRatio: number;
  effectivePerf: number;
  effectiveRt: number;
  /** How much performance is left on the table versus a full-power machine. */
  perfLostToTgp: number;
  perfPerDollar: number;
  perfPerInr: number;
  pixels: number;
}

export const DERIVED_LAPTOPS: DerivedLaptop[] = LAPTOPS.map((l) => {
  const gpu = LAPTOP_GPU_BY_ID[l.gpuId];
  const effectivePerf = perfAtTgp(gpu.perfAtMaxTgp, l.tgp, gpu.maxTgp);
  const effectiveRt = perfAtTgp(gpu.rtAtMaxTgp, l.tgp, gpu.maxTgp);
  const [w, h] = l.resolution.split(" x ").map(Number);
  return {
    ...l,
    gpu,
    tgpRatio: +(l.tgp / gpu.maxTgp).toFixed(3),
    effectivePerf,
    effectiveRt,
    perfLostToTgp: +(100 - (effectivePerf / gpu.perfAtMaxTgp) * 100).toFixed(0),
    perfPerDollar: +((effectivePerf / l.msrp) * 1000).toFixed(2),
    perfPerInr: +((effectivePerf / l.inr) * 100000).toFixed(2),
    pixels: w * h,
  };
});

export const LAPTOP_BRANDS: string[] = DERIVED_LAPTOPS.reduce<string[]>((acc, l) => {
  if (!acc.includes(l.brand)) acc.push(l.brand);
  return acc.sort();
}, []);

/** Laptop GPUs that at least one listed machine ships, in performance order. */
export const USED_LAPTOP_GPUS: LaptopGpu[] = LAPTOP_GPUS.filter((g) =>
  DERIVED_LAPTOPS.some((l) => l.gpuId === g.id),
).sort((a, b) => b.perfAtMaxTgp - a.perfAtMaxTgp);

export function laptopsForDesktopGpu(desktopId: string): DerivedLaptop[] {
  const families = LAPTOP_GPUS.filter((g) => g.desktopCousin === desktopId).map((g) => g.id);
  return DERIVED_LAPTOPS.filter((l) => families.includes(l.gpuId));
}
